export const countries = [
  { name: 'Afghanistan', short_name: 'Afghanistan', flag: '🇦🇫' },
  { name: 'Åland Islands', short_name: 'Åland Islands', flag: '🇦🇽' },
  { name: 'Albania', short_name: 'Albania', flag: '🇦🇱' },
  { name: 'Algeria', short_name: 'Algeria', flag: '🇩🇿' },
  { name: 'American Samoa', short_name: 'American Samoa', flag: '🇺🇸' },
  { name: 'Andorra', short_name: 'Andorra', flag: '🇦🇩' },
  { name: 'Angola', short_name: 'Angola', flag: '🇦🇴' },
  { name: 'Anguilla', short_name: 'Anguilla', flag: '🇦🇮' },
  { name: 'Antarctica', short_name: 'Antarctica', flag: '🇦🇶' },
  {
    name: 'Antigua and Barbuda',
    short_name: 'Antigua and Barbuda',
    flag: '🇦🇬',
  },
  { name: 'Argentina', short_name: 'Argentina', flag: '🇦🇷' },
  { name: 'Armenia', short_name: 'Armenia', flag: '🇦🇲' },
  { name: 'Aruba', short_name: 'Aruba', flag: '🇦🇼' },
  { name: 'Australia', short_name: 'Australia', flag: '🇦🇺' },
  { name: 'Austria', short_name: 'Austria', flag: '🇦🇹' },
  { name: 'Azerbaijan', short_name: 'Azerbaijan', flag: '🇦🇿' },
  { name: 'Bahamas', short_name: 'Bahamas', flag: '🇧🇸' },
  { name: 'Bahrain', short_name: 'Bahrain', flag: '🇧🇭' },
  { name: 'Bangladesh', short_name: 'Bangladesh', flag: '🇧🇩' },
  { name: 'Barbados', short_name: 'Barbados', flag: '🇧🇧' },
  { name: 'Belarus', short_name: 'Belarus', flag: '🇧🇾' },
  { name: 'Belgium', short_name: 'Belgium', flag: '🇧🇪' },
  { name: 'Belize', short_name: 'Belize', flag: '🇧🇿' },
  { name: 'Benin', short_name: 'Benin', flag: '🇧🇯' },
  { name: 'Bermuda', short_name: 'Bermuda', flag: '🇧🇲' },
  { name: 'Bhutan', short_name: 'Bhutan', flag: '🇧🇹' },
  {
    name: 'Bolivia, Plurinational State of Bolivia',
    short_name: 'Bolivia',
    flag: '🇧🇴',
  },
  {
    name: 'Bosnia and Herzegovina',
    short_name: 'Bosnia and Herzegovina',
    flag: '🇧🇦',
  },
  { name: 'Botswana', short_name: 'Botswana', flag: '🇧🇼' },
  { name: 'Bouvet Island', short_name: 'Bouvet Island', flag: '🏳' },
  { name: 'Brazil', short_name: 'Brazil', flag: '🇧🇷' },
  {
    name: 'British Indian Ocean Territory',
    short_name: 'British Indian Ocean Territory',
    flag: '🇮🇴',
  },
  { name: 'Brunei Darussalam', short_name: 'Brunei', flag: '🇧🇳' },
  { name: 'Bulgaria', short_name: 'Bulgaria', flag: '🇧🇬' },
  { name: 'Burkina Faso', short_name: 'Burkina Faso', flag: '🇧🇫' },
  { name: 'Burundi', short_name: 'Burundi', flag: '🇧🇮' },
  { name: 'Cambodia', short_name: 'Cambodia', flag: '🇰🇭' },
  { name: 'Cameroon', short_name: 'Cameroon', flag: '🇨🇲' },
  { name: 'Canada', short_name: 'Canada', flag: '🇨🇦' },
  { name: 'Cape Verde', short_name: 'Cape Verde', flag: '🇨🇻' },
  { name: 'Cayman Islands', short_name: 'Cayman Islands', flag: '🇰🇾' },
  {
    name: 'Central African Republic',
    short_name: 'Central African Republic',
    flag: '🇨🇫',
  },
  { name: 'Chad', short_name: 'Chad', flag: '🇹🇩' },
  { name: 'Chile', short_name: 'Chile', flag: '🇨🇱' },
  { name: 'China', short_name: 'China', flag: '🇨🇳' },
  { name: 'Christmas Island', short_name: 'Christmas Island', flag: '🇨🇽' },
  { name: 'Cocos (Keeling) Islands', short_name: 'Cocos Islands', flag: '🇨🇨' },
  { name: 'Colombia', short_name: 'Colombia', flag: '🇨🇴' },
  { name: 'Comoros', short_name: 'Comoros', flag: '🇰🇲' },
  { name: 'Congo', short_name: 'Congo', flag: '🇨🇬' },
  {
    name: 'Congo, The Democratic Republic of the Congo',
    short_name: 'DR Congo',
    flag: '🇨🇩',
  },
  { name: 'Cook Islands', short_name: 'Cook Islands', flag: '🇨🇰' },
  { name: 'Costa Rica', short_name: 'Costa Rica', flag: '🇨🇷' },
  { name: "Cote d'Ivoire", short_name: "Cote d'Ivoire", flag: '🇨🇮' },
  { name: 'Croatia', short_name: 'Croatia', flag: '🇭🇷' },
  { name: 'Cuba', short_name: 'Cuba', flag: '🇨🇺' },
  { name: 'Cyprus', short_name: 'Cyprus', flag: '🇨🇾' },
  { name: 'Czech Republic', short_name: 'Czech Republic', flag: '🇨🇿' },
  { name: 'Denmark', short_name: 'Denmark', flag: '🇩🇰' },
  { name: 'Djibouti', short_name: 'Djibouti', flag: '🇩🇯' },
  { name: 'Dominica', short_name: 'Dominica', flag: '🇩🇲' },
  { name: 'Dominican Republic', short_name: 'Dominican Republic', flag: '🇩🇴' },
  { name: 'Ecuador', short_name: 'Ecuador', flag: '🇪🇨' },
  { name: 'Egypt', short_name: 'Egypt', flag: '🇪🇬' },
  { name: 'El Salvador', short_name: 'El Salvador', flag: '🇸🇻' },
  { name: 'Equatorial Guinea', short_name: 'Equatorial Guinea', flag: '🇬🇶' },
  { name: 'Eritrea', short_name: 'Eritrea', flag: '🇪🇷' },
  { name: 'Estonia', short_name: 'Estonia', flag: '🇪🇪' },
  { name: 'Ethiopia', short_name: 'Ethiopia', flag: '🇪🇹' },
  {
    name: 'Falkland Islands (Malvinas)',
    short_name: 'Falkland Islands',
    flag: '🇫🇰',
  },
  { name: 'Faroe Islands', short_name: 'Faroe Islands', flag: '🇫🇴' },
  { name: 'Fiji', short_name: 'Fiji', flag: '🇫🇯' },
  { name: 'Finland', short_name: 'Finland', flag: '🇫🇮' },
  { name: 'France', short_name: 'France', flag: '🇫🇷' },
  { name: 'French Guiana', short_name: 'French Guiana', flag: '🇬🇫' },
  { name: 'French Polynesia', short_name: 'French Polynesia', flag: '🇵🇫' },
  {
    name: 'French Southern Territories',
    short_name: 'French Southern Territories',
    flag: '🇹🇫',
  },
  { name: 'Gabon', short_name: 'Gabon', flag: '🇬🇦' },
  { name: 'Gambia', short_name: 'Gambia', flag: '🇬🇲' },
  { name: 'Georgia', short_name: 'Georgia', flag: '🇬🇪' },
  { name: 'Germany', short_name: 'Germany', flag: '🇩🇪' },
  { name: 'Ghana', short_name: 'Ghana', flag: '🇬🇭' },
  { name: 'Gibraltar', short_name: 'Gibraltar', flag: '🇬🇮' },
  { name: 'Greece', short_name: 'Greece', flag: '🇬🇷' },
  { name: 'Greenland', short_name: 'Greenland', flag: '🇬🇱' },
  { name: 'Grenada', short_name: 'Grenada', flag: '🇬🇩' },
  { name: 'Guadeloupe', short_name: 'Guadeloupe', flag: '🇬🇵' },
  { name: 'Guam', short_name: 'Guam', flag: '🇬🇺' },
  { name: 'Guatemala', short_name: 'Guatemala', flag: '🇬🇹' },
  { name: 'Guernsey', short_name: 'Guernsey', flag: '🇬🇬' },
  { name: 'Guinea', short_name: 'Guinea', flag: '🇬🇳' },
  { name: 'Guinea-Bissau', short_name: 'Guinea-Bissau', flag: '🇬🇼' },
  { name: 'Guyana', short_name: 'Guyana', flag: '🇬🇾' },
  { name: 'Haiti', short_name: 'Haiti', flag: '🇭🇹' },
  {
    name: 'Heard Island and McDonald Islands',
    short_name: 'Heard Island',
    flag: '🏳',
  },
  {
    name: 'Holy See (Vatican City State)',
    short_name: 'Vatican City',
    flag: '🇻🇦',
  },
  { name: 'Honduras', short_name: 'Honduras', flag: '🇭🇳' },
  { name: 'Hong Kong', short_name: 'Hong Kong', flag: '🇭🇰' },
  { name: 'Hungary', short_name: 'Hungary', flag: '🇭🇺' },
  { name: 'Iceland', short_name: 'Iceland', flag: '🇮🇸' },
  { name: 'India', short_name: 'India', flag: '🇮🇳' },
  { name: 'Indonesia', short_name: 'Indonesia', flag: '🇮🇩' },
  { name: 'Iran, Islamic Republic of', short_name: 'Iran', flag: '🇮🇷' },
  { name: 'Iraq', short_name: 'Iraq', flag: '🇮🇶' },
  { name: 'Ireland', short_name: 'Ireland', flag: '🇮🇪' },
  { name: 'Isle of Man', short_name: 'Isle of Man', flag: '🇮🇲' },
  { name: 'Israel', short_name: 'Israel', flag: '🇮🇱' },
  { name: 'Italy', short_name: 'Italy', flag: '🇮🇹' },
  { name: 'Jamaica', short_name: 'Jamaica', flag: '🇯🇲' },
  { name: 'Japan', short_name: 'Japan', flag: '🇯🇵' },
  { name: 'Jersey', short_name: 'Jersey', flag: '🇯🇪' },
  { name: 'Jordan', short_name: 'Jordan', flag: '🇯🇴' },
  { name: 'Kazakhstan', short_name: 'Kazakhstan', flag: '🇰🇿' },
  { name: 'Kenya', short_name: 'Kenya', flag: '🇰🇪' },
  { name: 'Kiribati', short_name: 'Kiribati', flag: '🇰🇮' },
  {
    name: "Korea, Democratic People's Republic of",
    short_name: 'North Korea',
    flag: '🇰🇵',
  },
  { name: 'Korea, Republic of', short_name: 'South Korea', flag: '🇰🇷' },
  { name: 'Kosovo', short_name: 'Kosovo', flag: '🇽🇰' },
  { name: 'Kuwait', short_name: 'Kuwait', flag: '🇰🇼' },
  { name: 'Kyrgyzstan', short_name: 'Kyrgyzstan', flag: '🇰🇬' },
  { name: "Lao People's Democratic Republic", short_name: 'Laos', flag: '🇱🇦' },
  { name: 'Latvia', short_name: 'Latvia', flag: '🇱🇻' },
  { name: 'Lebanon', short_name: 'Lebanon', flag: '🇱🇧' },
  { name: 'Lesotho', short_name: 'Lesotho', flag: '🇱🇸' },
  { name: 'Liberia', short_name: 'Liberia', flag: '🇱🇷' },
  { name: 'Libya', short_name: 'Libya', flag: '🇱🇾' },
  { name: 'Liechtenstein', short_name: 'Liechtenstein', flag: '🇱🇮' },
  { name: 'Lithuania', short_name: 'Lithuania', flag: '🇱🇹' },
  { name: 'Luxembourg', short_name: 'Luxembourg', flag: '🇱🇺' },
  { name: 'Macao', short_name: 'Macao', flag: '🇲🇴' },
  { name: 'Macedonia, Republic of', short_name: 'North Macedonia', flag: '🇲🇰' },
  { name: 'Madagascar', short_name: 'Madagascar', flag: '🇲🇬' },
  { name: 'Malawi', short_name: 'Malawi', flag: '🇲🇼' },
  { name: 'Malaysia', short_name: 'Malaysia', flag: '🇲🇾' },
  { name: 'Maldives', short_name: 'Maldives', flag: '🇲🇻' },
  { name: 'Mali', short_name: 'Mali', flag: '🇲🇱' },
  { name: 'Malta', short_name: 'Malta', flag: '🇲🇹' },
  { name: 'Marshall Islands', short_name: 'Marshall Islands', flag: '🇲🇭' },
  { name: 'Martinique', short_name: 'Martinique', flag: '🇲🇶' },
  { name: 'Mauritania', short_name: 'Mauritania', flag: '🇲🇷' },
  { name: 'Mauritius', short_name: 'Mauritius', flag: '🇲🇺' },
  { name: 'Mayotte', short_name: 'Mayotte', flag: '🇾🇹' },
  { name: 'Mexico', short_name: 'Mexico', flag: '🇲🇽' },
  {
    name: 'Micronesia, Federated States of',
    short_name: 'Micronesia',
    flag: '🇫🇲',
  },
  { name: 'Moldova, Republic of', short_name: 'Moldova', flag: '🇲🇩' },
  { name: 'Monaco', short_name: 'Monaco', flag: '🇲🇨' },
  { name: 'Mongolia', short_name: 'Mongolia', flag: '🇲🇳' },
  { name: 'Montenegro', short_name: 'Montenegro', flag: '🇲🇪' },
  { name: 'Montserrat', short_name: 'Montserrat', flag: '🇲🇸' },
  { name: 'Morocco', short_name: 'Morocco', flag: '🇲🇦' },
  { name: 'Mozambique', short_name: 'Mozambique', flag: '🇲🇿' },
  { name: 'Myanmar', short_name: 'Myanmar', flag: '🇲🇲' },
  { name: 'Namibia', short_name: 'Namibia', flag: '🇳🇦' },
  { name: 'Nauru', short_name: 'Nauru', flag: '🇳🇷' },
  { name: 'Nepal', short_name: 'Nepal', flag: '🇳🇵' },
  { name: 'Netherlands', short_name: 'Netherlands', flag: '🇳🇱' },
  { name: 'New Caledonia', short_name: 'New Caledonia', flag: '🇳🇨' },
  { name: 'New Zealand', short_name: 'New Zealand', flag: '🇳🇿' },
  { name: 'Nicaragua', short_name: 'Nicaragua', flag: '🇳🇮' },
  { name: 'Niger', short_name: 'Niger', flag: '🇳🇪' },
  { name: 'Nigeria', short_name: 'Nigeria', flag: '🇳🇬' },
  { name: 'Niue', short_name: 'Niue', flag: '🇳🇺' },
  { name: 'Norfolk Island', short_name: 'Norfolk Island', flag: '🇳🇫' },
  {
    name: 'Northern Mariana Islands',
    short_name: 'Northern Mariana Islands',
    flag: '🏳',
  },
  { name: 'Norway', short_name: 'Norway', flag: '🇳🇴' },
  { name: 'Oman', short_name: 'Oman', flag: '🇴🇲' },
  { name: 'Pakistan', short_name: 'Pakistan', flag: '🇵🇰' },
  { name: 'Palau', short_name: 'Palau', flag: '🇵🇼' },
  {
    name: 'Palestinian Territory, Occupied',
    short_name: 'Palestine',
    flag: '🇵🇸',
  },
  { name: 'Panama', short_name: 'Panama', flag: '🇵🇦' },
  { name: 'Papua New Guinea', short_name: 'Papua New Guinea', flag: '🇵🇬' },
  { name: 'Paraguay', short_name: 'Paraguay', flag: '🇵🇾' },
  { name: 'Peru', short_name: 'Peru', flag: '🇵🇪' },
  { name: 'Philippines', short_name: 'Philippines', flag: '🇵🇭' },
  { name: 'Pitcairn', short_name: 'Pitcairn', flag: '🇵🇳' },
  { name: 'Poland', short_name: 'Poland', flag: '🇵🇱' },
  { name: 'Portugal', short_name: 'Portugal', flag: '🇵🇹' },
  { name: 'Puerto Rico', short_name: 'Puerto Rico', flag: '🇵🇷' },
  { name: 'Qatar', short_name: 'Qatar', flag: '🇶🇦' },
  { name: 'Reunion', short_name: 'Reunion', flag: '🇫🇷' },
  { name: 'Romania', short_name: 'Romania', flag: '🇷🇴' },
  { name: 'Russian Federation', short_name: 'Russia', flag: '🇷🇺' },
  { name: 'Rwanda', short_name: 'Rwanda', flag: '🇷🇼' },
  { name: 'Saint Barthelemy', short_name: 'Saint Barthelemy', flag: '🇧🇱' },
  {
    name: 'Saint Helena, Ascension and Tristan da Cunha',
    short_name: 'Saint Helena',
    flag: '🇸🇭',
  },
  {
    name: 'Saint Kitts and Nevis',
    short_name: 'Saint Kitts and Nevis',
    flag: '🇰🇳',
  },
  { name: 'Saint Lucia', short_name: 'Saint Lucia', flag: '🇱🇨' },
  { name: 'Saint Martin (French part)', short_name: 'Saint Martin', flag: '🏳' },
  {
    name: 'Saint Pierre and Miquelon',
    short_name: 'Saint Pierre and Miquelon',
    flag: '🇵🇲',
  },
  {
    name: 'Saint Vincent and the Grenadines',
    short_name: 'Saint Vincent and the Grenadines',
    flag: '🇻🇨',
  },
  { name: 'Samoa', short_name: 'Samoa', flag: '🇼🇸' },
  { name: 'San Marino', short_name: 'San Marino', flag: '🇸🇲' },
  {
    name: 'Sao Tome and Principe',
    short_name: 'Sao Tome and Principe',
    flag: '🇸🇹',
  },
  { name: 'Saudi Arabia', short_name: 'KSA', flag: '🇸🇦' },
  { name: 'Senegal', short_name: 'Senegal', flag: '🇸🇳' },
  { name: 'Serbia', short_name: 'Serbia', flag: '🇷🇸' },
  { name: 'Seychelles', short_name: 'Seychelles', flag: '🇸🇨' },
  { name: 'Sierra Leone', short_name: 'Sierra Leone', flag: '🇸🇱' },
  { name: 'Singapore', short_name: 'Singapore', flag: '🇸🇬' },
  { name: 'Slovakia', short_name: 'Slovakia', flag: '🇸🇰' },
  { name: 'Slovenia', short_name: 'Slovenia', flag: '🇸🇮' },
  { name: 'Solomon Islands', short_name: 'Solomon Islands', flag: '🇸🇧' },
  { name: 'Somalia', short_name: 'Somalia', flag: '🇸🇴' },
  { name: 'South Africa', short_name: 'South Africa', flag: '🇿🇦' },
  {
    name: 'South Georgia and the South Sandwich Islands',
    short_name: 'South Georgia',
    flag: '🇬🇸',
  },
  { name: 'South Sudan', short_name: 'South Sudan', flag: '🇸🇸' },
  { name: 'Spain', short_name: 'Spain', flag: '🇪🇸' },
  { name: 'Sri Lanka', short_name: 'Sri Lanka', flag: '🇱🇰' },
  { name: 'Sudan', short_name: 'Sudan', flag: '🇸🇩' },
  { name: 'Suriname', short_name: 'Suriname', flag: '🇸🇷' },
  {
    name: 'Svalbard and Jan Mayen',
    short_name: 'Svalbard and Jan Mayen',
    flag: '🇩🇰',
  },
  { name: 'Swaziland', short_name: 'Swaziland', flag: '🇸🇿' },
  { name: 'Sweden', short_name: 'Sweden', flag: '🇸🇪' },
  { name: 'Switzerland', short_name: 'Switzerland', flag: '🇨🇭' },
  { name: 'Syrian Arab Republic', short_name: 'Syria', flag: '🇸🇾' },
  { name: 'Taiwan, Province of China', short_name: 'Taiwan', flag: '🇹🇼' },
  { name: 'Tajikistan', short_name: 'Tajikistan', flag: '🇹🇯' },
  { name: 'Tanzania, United Republic of', short_name: 'Tanzania', flag: '🇹🇿' },
  { name: 'Thailand', short_name: 'Thailand', flag: '🇹🇭' },
  { name: 'Timor-Leste', short_name: 'Timor-Leste', flag: '🇹🇱' },
  { name: 'Togo', short_name: 'Togo', flag: '🇹🇬' },
  { name: 'Tokelau', short_name: 'Tokelau', flag: '🇹🇰' },
  { name: 'Tonga', short_name: 'Tonga', flag: '🇹🇴' },
  {
    name: 'Trinidad and Tobago',
    short_name: 'Trinidad and Tobago',
    flag: '🇹🇹',
  },
  { name: 'Tunisia', short_name: 'Tunisia', flag: '🇹🇳' },
  { name: 'Turkey', short_name: 'Turkey', flag: '🇹🇷' },
  { name: 'Turkmenistan', short_name: 'Turkmenistan', flag: '🇹🇲' },
  {
    name: 'Turks and Caicos Islands',
    short_name: 'Turks and Caicos Islands',
    flag: '🇹🇨',
  },
  { name: 'Tuvalu', short_name: 'Tuvalu', flag: '🇹🇻' },
  { name: 'Uganda', short_name: 'Uganda', flag: '🇺🇬' },
  { name: 'Ukraine', short_name: 'Ukraine', flag: '🇺🇦' },
  { name: 'United Arab Emirates', short_name: 'UAE', flag: '🇦🇪' },
  { name: 'United Kingdom', short_name: 'UK', flag: '🇬🇧' },
  { name: 'United States', short_name: 'USA', flag: '🇺🇸' },
  { name: 'Uruguay', short_name: 'Uruguay', flag: '🇺🇾' },
  { name: 'Uzbekistan', short_name: 'Uzbekistan', flag: '🇺🇿' },
  { name: 'Vanuatu', short_name: 'Vanuatu', flag: '🇻🇺' },
  {
    name: 'Venezuela, Bolivarian Republic of',
    short_name: 'Venezuela',
    flag: '🇻🇪',
  },
  { name: 'Vietnam', short_name: 'Vietnam', flag: '🇻🇳' },
  {
    name: 'Virgin Islands, British',
    short_name: 'British Virgin Islands',
    flag: '🇻🇬',
  },
  {
    name: 'Virgin Islands, U.S.',
    short_name: 'U.S. Virgin Islands',
    flag: '🇻🇮',
  },
  { name: 'Wallis and Futuna', short_name: 'Wallis and Futuna', flag: '🇼🇫' },
  { name: 'Yemen', short_name: 'Yemen', flag: '🇾🇪' },
  { name: 'Zambia', short_name: 'Zambia', flag: '🇿🇲' },
  { name: 'Zimbabwe', short_name: 'Zimbabwe', flag: '🇿🇼' },
];
